// Time in seconds between retry attempts from recoverable errors
const RETRY_INTERVAL = 5;
const DEFAULT_TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE = '123';
const DEFAULT_TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE = '321';

export {
  RETRY_INTERVAL,
  DEFAULT_TEST_CENTRALIZED_EXCHANGE_QUOTEASSET_BALANCE,
  DEFAULT_TEST_CENTRALIZED_EXCHANGE_BASEASSET_BALANCE,
};
